# Generated by Django 3.0.3 on 2020-02-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='file',
            field=models.FileField(default='default', upload_to=''),
            preserve_default=False,
        ),
    ]
