# Generated by Django 3.0.3 on 2020-02-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wrong_probs',
            field=models.ManyToManyField(default=None, related_name='wrong_problems', to='problems.Problems'),
        ),
    ]
